destination: ./_site
exclude: [
	'CNAME',
	'README.md',
    'Gemfile',
    'Gemfile.lock',
    '*.sublime-*',
    'bin/',
    'less/'
]
markdown: rdiscount
permalink: /posts/:title
rdiscount:
extensions: [smart]
gems:
- jekyll-sitemap
name: John Berberich
url: http://johnberberich.com
description: A fantastic blog that is fantastic.
twitter: johnberberich
