title:       John Berberich
tagline:     Foo
description: A fantastic blog that is fantastic.
url:         http://johnberberich.com
baseurl:     /

google_analytics:         UA-35929716-1
google_site_verification: oTmLIeNN96Rw9Xv70CTpsVzkQJMCuTqe3GllV01s-5A

author:
  name:  John Berberich
  email: jberberich@gmail.com

exclude: [
  'CNAME',
  'README.md',
  'Gemfile',
  'Gemfile.lock',
  '*.sublime-*',
  'bin/',
  'less/'
]

# Dependencies
markdown:    rdiscount
highlighter: false

# Permalinks
permalink:           pretty
relative_permalinks: false

sass:
  style: :compressed

gems:
- jekyll-sitemap

github:
  repo:  https://github.com/johnberberich/johnberberich.github.io

version: 2.0.0
